name: build
on:
  push:
  pull_request:
  schedule:
    - cron: '0 8 * * 6'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout LFS objects
        run: git lfs pull
      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v0
      - name: Run script
        uses: matlab-actions/run-command@v0
        with:
          command: cd('src'), calculate_kinematics